services:
  app_back_pensionados:
    build: ./src/main/resources
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db_pensionados_dl:3306/cuotapartes_pensionados_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      db_pensionados_dl:
        condition: service_healthy
  db_pensionados_dl:
    image: mysql:8.0.40
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: cuotapartes_pensionados_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10