name: CI - Maven Tests

on:
  push:
    branches: [ 'schanchi', 'ci/add-github-actions' ]
  pull_request:
    branches: [ 'schanchi', 'ci/add-github-actions' ]
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test
      # Definicion de variables auxiliares
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: cuotapartes_pensionados_db
      DB_USER: root
      DB_PASSWORD: root

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Make mvnw executable (if present)
        run: |
          if [ -f mvnw ]; then chmod +x mvnw; fi

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" --password=root --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run unit tests (Maven)
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}
          SPRING_DATASOURCE_USERNAME: ${{ env.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.DB_PASSWORD }}
        run: |
          if [ -f mvnw ]; then ./mvnw -B -V -e test; else mvn -B -V -e test; fi

      - name: Upload surefire reports (so you can download them)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
